pipeline {
    agent { label 'ci-agent' } 
    stages {
        stage('deploy web-server'){
            steps {
                container('kubectl'){
                   sh "kubectl delete deployment $deploymentName -n web"
                   sh "kubectl delete svc $serviceName -n web"
                }
            }
        }
    }
}
