pipeline {
    agent { label 'ci-agent' } 
    stages {
        stage('deploy web-server'){
            steps {
                container('kubectl'){
                   sh 'kubectl delete deployment nginx-deployment -n web'
                   sh 'kubectl delete svc service-nginx -n web'
                }
            }
        }
    }
}
