pipeline {
    agent { label 'ci-agent' } 
    stages {
        stage('scale web-server'){
            steps {
                container('kubectl'){
                   sh "kubectl scale --replicas=$podCount deployment/nginx-deployment -n web"
                }
            }
        }
    }
}