pipeline {
    agent { label 'ci-agent' } 
    stages {
        stage('delete web-server'){
            steps {
                container('kubectl'){
                    dir('buildImagePipeline') {
                        sh 'kubectl apply -f pod.yaml'
                    }
                }
            }
        }
    }
}