pipeline {
    agent { label 'ci-agent' } 
    stages {
        stage('delete web-server'){
            steps {
                container('docker'){
                    dir('buildImagePipeline') {
                        sh 'docker build -t hostname .'
                        sh 'docker image ls'
                    }
                }
            }
        }
    }
}