pipeline {
    agent { label 'ci-agent' } 
    stages {
        stage('delete web-server'){
            steps {
                container('kubectl'){

                }
            }
        }
    }
}